"""update recipe ratings to likes

Revision ID: 11dba874c811
Revises: e67af17dd4c6
Create Date: 2019-09-28 19:53:19.337987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11dba874c811'
down_revision = 'e67af17dd4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe') as batch_op:
        batch_op.drop_column('rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('rating', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
