"""add likes

Revision ID: 30d57b5afc37
Revises: ef6cc29c66e7
Create Date: 2019-09-29 12:25:52.406501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d57b5afc37'
down_revision = 'ef6cc29c66e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('username', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_likes_recipe_id_recipe')),
    sa.ForeignKeyConstraint(['username'], ['user.username'], name=op.f('fk_likes_username_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
