"""add difficulty to recipe

Revision ID: 7f94bebbaa9f
Revises: f6515f76543f
Create Date: 2019-09-29 09:10:12.719263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f94bebbaa9f'
down_revision = 'f6515f76543f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('likes')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
