"""add image metadata

Revision ID: 99394b91d7af
Revises: 0421471e1f95
Create Date: 2019-11-10 10:25:23.018084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99394b91d7af'
down_revision = '0421471e1f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_image_recipe_id_recipe'), 'recipe', ['recipe_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_image_recipe_id_recipe'), type_='foreignkey')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###
