"""add following join table

Revision ID: a5ae58d5993d
Revises: 8dab4679420b
Create Date: 2019-09-30 18:28:27.669529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ae58d5993d'
down_revision = '8dab4679420b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_following',
    sa.Column('user_username', sa.Integer(), nullable=False),
    sa.Column('following_username', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['following_username'], ['user.username'], name=op.f('fk_user_following_following_username_user')),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], name=op.f('fk_user_following_user_username_user')),
    sa.PrimaryKeyConstraint('user_username', 'following_username', name=op.f('pk_user_following'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_following')
    # ### end Alembic commands ###
