"""create challenges

Revision ID: d233f8d16e49
Revises: db218c826aed
Create Date: 2019-10-27 19:10:41.755073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd233f8d16e49'
down_revision = 'db218c826aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_challenge_recipe_id_recipe'), 'recipe', ['recipe_id'], ['id'])

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipe_challenge_id_challenge', type_='foreignkey')
        batch_op.drop_column('challenge_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_recipe_challenge_id_challenge', 'challenge', ['challenge_id'], ['id'])

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_challenge_recipe_id_recipe'), type_='foreignkey')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###
