"""change featured image

Revision ID: d749e7ad6653
Revises: 99394b91d7af
Create Date: 2019-11-10 11:32:16.174823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd749e7ad6653'
down_revision = '99394b91d7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_image', sa.Integer(), nullable=True))
        batch_op.drop_column('featured_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('f_image')

    # ### end Alembic commands ###
