"""normalize tables

Revision ID: e1c3d1a81438
Revises: c2913fc17416
Create Date: 2019-10-11 14:13:22.834177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c3d1a81438'
down_revision = 'c2913fc17416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_ingredient_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('recipe_id', 'number', name=op.f('pk_ingredient'))
    )
    op.create_table('step',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('annotation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_step_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('recipe_id', 'number', name=op.f('pk_step'))
    )
    op.drop_table('annotation')
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('ingredients')
        batch_op.drop_column('steps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steps', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True))

    op.create_table('annotation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('placement', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='fk_annotation_recipe_id_recipe'),
    sa.PrimaryKeyConstraint('id', name='pk_annotation')
    )
    op.drop_table('step')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
