"""update recipe model

Revision ID: e67af17dd4c6
Revises: 753a931e94f0
Create Date: 2019-09-14 11:18:59.412975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67af17dd4c6'
down_revision = '753a931e94f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'rating')
    # ### end Alembic commands ###
