"""keep count of remixes

Revision ID: ef6cc29c66e7
Revises: 5f2f0497a5c2
Create Date: 2019-09-29 10:55:18.114336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6cc29c66e7'
down_revision = '5f2f0497a5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('remixcount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remixcount', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
